### ISSUE TITLE
SetAllowFlight is always true. 

### ISSUE THREAD

**Issue by SuixideBunneh** [ChiefMoneyBags/TempFly#2]
Hello,

I have new player joining and I dont really know where they got setallowflight to true. I checked and they have 0s of flying time but on Skyblock, they were able to fly. I already set superior.island.fly to false, essentials.fly to false so do you think its from your plugin that they got the allowflight to true all the time? 

I will check again tomorrow just to confirm.

**Comment by SuixideBunneh** [comment]
Also, one thing, I have tried this today. I got flytime. So, initially, I have setAllowFlight to false. When I enabled fly, I can see that setaAllowFlight changed to true, which is correct. When turn off my fly again using /fly, my setAllowFlight stays true. I am expecting that the setAllowFlight changed to false when Flight is disabled. Thanks

**Comment by ChiefMoneyBags** [comment]
It is correct that while a player has tempfly active getAllowFlight() will remain true, even if you try setting it to false. You must first remove the players tempfly status to setAllowFlight(false). As for the new player having allow flight true on join i will look into some possible answers and test if it is tempfly.

**Comment by ChiefMoneyBags** [comment]
Also removing a players tempfly will automatically setAllowFlight(false) unless the player is in gamemode CREATIVE or SPECTATOR

**Comment by SuixideBunneh** [comment]
Do you think its because in Flyer.class on line 42, that the player have p.setAllowFlight always to true?

**Comment by SuixideBunneh** [comment]
I found a new lead.

When I am OP, I fly, floating in the air, then I set my time fly to 5 seconds. As soon as 5 seconds over, it will terminate my fly, send me back to the ground and it says " You have no more flight time". Doing /tf still give me the same message. I checked and it shows that my setAllowFlight(false). Which is correct.

When I am not OP, I fly, floating in the air, then I set my time fly to 5 seconds. As soon as 5 seconds over, it will terminate my fly, send me back to the ground and it says " You have no more flight time". Doing /tf still give me the same message. Then, I checked and it shows that my setAllowFlight is still set to true. Which is not correct. Could it be permission issue?

**Comment by ChiefMoneyBags** [comment]
While testing this i did find an issue but i'm not sure if it is the cause of your problem. 
I have a feature called flight disconnect that will regain a players fly after a server reload or after logging out. It was not checking if the player had fly time before setting allow flight to true. This would allow the player to login and fly for 1 second before allow flight was disabled again.

**Comment by ChiefMoneyBags** [comment]
I pushed the fix if you want to compile the jar and test if it fixes your problem

**Comment by SuixideBunneh** [comment]
There is a problem on WorldGuardAPI. java. I dont think I can compile this.Btw, I have all the dependency as well.

![image](https://user-images.githubusercontent.com/56784812/75980422-6320b680-5f1d-11ea-8c7d-55588b38ba9a.png)

**Comment by SuixideBunneh** [comment]
Hi, I managed to compile and tested. Behavior is still the same as in this comment:

"I found a new lead.

When I am OP, I fly, floating in the air, then I set my time fly to 5 seconds. As soon as 5 seconds over, it will terminate my fly, send me back to the ground and it says " You have no more flight time". Doing /tf still give me the same message. I checked and it shows that my setAllowFlight(false). Which is correct.

When I am not OP, I fly, floating in the air, then I set my time fly to 5 seconds. As soon as 5 seconds over, it will terminate my fly, send me back to the ground and it says " You have no more flight time". Doing /tf still give me the same message. Then, I checked and it shows that my setAllowFlight is still set to true. Which is not correct. Could it be permission issue?"

**Comment by ChiefMoneyBags** [comment]
I cannot recreate the issue you are explaining it works fine when I compile and test it. Have you tried to test it on a clean server without other plugins?

**Comment by ChiefMoneyBags** [comment]
What permissions do you have when the problem happens

**Comment by SuixideBunneh** [comment]
Hey, I found out the issue. I have tested this on my test server. Its actually because of my world guard flags that set the fly to true. When I have OP, I bypass the flags of world guard, so it goes back to default. That is why it works fine when I am OP. 

I apologize for causing you so much inconvenience. And I appreciate your efforts on this. Thanks!
